[package]
name = "slint_rtsp"
version = "0.1.0"
edition = "2024"
build = "src/build.rs"

[dependencies]
slint = "1.16.1"
ffmpeg-next = "8.0.0"
smol = "2.0.0"
anyhow = "1.0"
futures = "0.3.31"
cpal = "0.15.3"
ringbuf = "0.3.3"
bytemuck = "1.23.1"
derive_more = { version = "2.0.1", features = ["deref", "deref_mut"] }
chrono = "0.4.45"
sysinfo = "0.38.4"
env_logger = "0.11.10"
log = "0.4.32"
libc = "0.2.186"
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png", "pnm", "webp"] }
reqwest = { version = "0.12.25", default-features = false, features = ["blocking", "rustls-tls"] }

[build-dependencies]
slint-build = "1.16.1"
