import { VerticalBox, Palette } from "std-widgets.slint";

export component App inherits Window {
    in property <image> video-frame <=> image.source;
    in property <bool> playing;

    callback toggle-pause-play();

    preferred-width: 1280px;
    preferred-height: 534px;
    min-width: 854px;
    min-height: 480px;
    title: "Slint FFmpeg Video Playback";
    background: #000000;

    states [
        shown when !playing || controls-area.has-hover: {
            controls.opacity: 1;
            in {
                animate controls.opacity { duration: 500ms; }
            }
        }
        hidden when playing: {
            controls.opacity: 0;
        }
    ]

    VerticalBox {
        image := Image {
            width: 100%;
            height: 100%;
        }
    }

    area := TouchArea {
        width: 100%;
        height: 100%;

        clicked => {
            root.toggle-pause-play();
        }

        controls := Rectangle {
            width: 160px;
            height: 90px;
            x: (root.width - self.width) / 2;
            y: root.height - self.height - 40px;
            border-radius: 4px;
            background: Palette.color-scheme == ColorScheme.dark ? #3737378c : #ffffff82;

            play-pause := Image {
                width: 64px;
                height: 64px;
                source: root.playing ? @image-url("../static/pause.svg") : @image-url("../static/play.svg");
            }

            controls-area := TouchArea {
                clicked => {
                    root.toggle-pause-play();
                }
            }
        }
    }
}
