export struct LogMessage {
    time: string,
    level: string,
    message: string,
    detail: string,
    image_url: string,
    snapshot: image,
}

export struct AlarmMessage {
    time: string,
    level: string,
    message: string,
    status: string,
    detail: string,
    image_url: string,
    snapshot: image,
}

export struct FoodItem {
    name: string,
    category: string,
    zone: string,
    quantity: string,
    temperature: string,
    expiry: string,
    status: string,
}
