import { HorizontalBox } from "std-widgets.slint";
import { UIconButton, UText } from "../sleek-ui/widgets.slint";

export component TopBar inherits HorizontalBox {
    in property <string> system-time;
    in property <string> stream-error;
    in property <string> video-url;
    callback close-requested();

    padding: 0px;
    alignment: space-between;

    HorizontalBox {
        spacing: 12px;
        padding: 0px;
        alignment: start;

        UText {
            text: "智能冷柜显示终端";
            font-size: 16px;
            font-weight: 700;
            color: #333333;
            vertical-alignment: center;
        }
    }

    HorizontalBox {
        spacing: 24px;
        padding: 0px;
        alignment: start;

        HorizontalBox {
            spacing: 8px;
            padding: 0px;
            height: 24px;

            Rectangle {
                width: 10px;
                background: transparent;

                Rectangle {
                    width: 10px;
                    height: 10px;
                    border-radius: 5px;
                    background: root.stream-error == "" ? #52c41a : #ff4d4f;
                }
            }

            UText {
                text: root.stream-error == "" ? "柜内摄像头在线" : "摄像头异常";
                color: #333333;
                vertical-alignment: center;
            }
        }

        UText {
            text: root.video-url;
            color: #666666;
            vertical-alignment: center;
        }
    }

    HorizontalBox {
        spacing: 8px;
        padding: 0px;
        alignment: end;

        UText {
            text: root.system-time;
            vertical-alignment: center;
            color: #666666;
        }

        UIconButton {
            variant: text;
            danger: true;
            icon: @image-url("../sleek-ui/assets/icons/x.svg");
            accessible-label: "关闭程序";
            clicked => {
                root.close-requested();
            }
        }
    }
}
